version: '3.8'

services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
        - "80:80"
  server:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: api  
    ports:
        - "3000:3000"
    environment:
        - NODE_ENV=production